# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xu01's blog
email: lingyi_xu@hotmail.com
description: Just a coder
baseurl: ""
url: "http://xu01.github.io" # the base hostname & protocol for your site
twitter_username: xu01
github_username:  xu01

# Build settings
markdown: kramdown
